version: '3'

services:
  mysql_dev:
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
  mysql_test:
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - '13306:3306'
  client:
    build:
      context: rails/client
      dockerfile: Dockerfile
    working_dir: /rails/client
    command: yarn run watch
    volumes:
      - ./rails/client:/rails/client
      - ./rails/app/javascript:/rails/app/javascript
  backend:
    build:
      context: rails
      dockerfile: Dockerfile
    working_dir: /rails
    ports:
      - '3000:3000'
    command: bundle exec rails server -b 0.0.0.0
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      RAILS_DATABASE_HOST: mysql_dev
      RAILS_TEST_DATABASE_HOST: mysql_test
      RAILS_TEST_DATABASE_PORT: 3306
    depends_on:
      - mysql_dev
      - mysql_test
      - client
    volumes:
      - ./rails:/rails
