version: '3'

services:
  mysql_dev:
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
  mysql_test:
    build:
      context: mysql
      dockerfile: Dockerfile
    ports:
      - '13306:3306'
  backend:
    build:
      context: rails
      dockerfile: Dockerfile
    working_dir: /rails
    ports:
      - '3000:3000'
    command: bundle exec rails server -b 0.0.0.0
    environment:
      TZ: Asia/Tokyo
      LANG: C.UTF-8
    depends_on:
      - mysql_dev
      - mysql_test
    volumes:
      - ./rails:/rails
