default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: r04
  username: rails_app
  password: password

development:
  <<: *default
  host: <%= ENV.fetch('RAILS_DATABASE_HOST') { 'mysql_dev' } %>

test:
  <<: *default
  host: <%= ENV.fetch('RAILS_DATABASE_HOST') { 'mysql_test' } %>

production:
  <<: *default
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
