openapi: 3.0.3

info:
  version: 1.0.0
  title: r04 API

paths:
  /api/v1/suppliers:
    get:
      operationId: getSuppliers
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - suppliers
                properties:
                  suppliers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Supplier"
    post:
      operationId: postSupplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supplier
              properties:
                supplier:
                  $ref: "#/components/schemas/SupplierParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - supplier
                properties:
                  supplier:
                    $ref: "#/components/schemas/Supplier"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
  /api/v1/suppliers/{id}:
    get:
      operationId: getSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - supplier
                properties:
                  supplier:
                    $ref: "#/components/schemas/Supplier"
    patch:
      operationId: patchSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supplier
              properties:
                supplier:
                  $ref: "#/components/schemas/SupplierParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - supplier
                properties:
                  supplier:
                    $ref: "#/components/schemas/Supplier"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
    delete:
      operationId: deleteSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"

  /api/v1/orders:
    get:
      operationId: getOrders
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
              required:
                - orders
              properties:
                orders:
                  type: array
                  items:
                    $ref: "#/components/schemas/Order"
    post:
      operationId: postOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - order
              properties:
                order:
                  $ref: "#/components/schemas/OrderParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - order
                properties:
                  order:
                    $ref: "#/components/schemas/Order"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string

  /api/v1/orders/${id}:
    get:
      operationId: getOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - order
                properties:
                  order:
                    $ref: "#/components/schemas/Order"

  /api/v1/suppliers/${supplierId}/products:
    get:
      operationId: getProducts
      parameters:
        - name: supplierId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - products
                properties:
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
    post:
      operationId: postProduct
      parameters:
        - name: supplier_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product
              properties:
                product:
                  $ref: "#/components/schemas/ProductParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - product
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
  /api/v1/products/${id}:
    get:
      operationId: getProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - product
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
    patch:
      operationId: patchProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product
              properties:
                product:
                  $ref: "#/components/schemas/ProductParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - product
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
    delete:
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"

components:
  schemas:
    Supplier:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Order:
      type: object
      required:
        - id
        - name
        - supplier_id
        - created_at
        - order_details
      properties:
        id:
          type: integer
        name:
          type: string
        supplier_id:
          type: integer
        created_at:
          type: string
        order_details:
          type: array
          items:
            $ref: "#/components/schemas/OrderDetail"
    OrderDetail:
      type: object
      required:
        - id
        - name
        - quantity
        - product_id
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: number
        product_id:
          type: integer

    SupplierParams:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    ProductParams:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    OrderParams:
      type: object
      required:
        - supplier_id
        - order_details
      properties:
        supplier_id:
          type: integer
        order_details:
          type: array
          items:
            $ref: "#/components/schemas/OrderDetailParams"
    OrderDetailParams:
      type: object
      required:
        - quantity
        - product_id
      properties:
        quantity:
          type: number
        product_id:
          type: integer
