openapi: 3.0.3

info:
  version: 1.0.0
  title: r04 API

paths:
  /api/v1/suppliers:
    get:
      operationId: getSuppliers
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - suppliers
                properties:
                  suppliers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Supplier"
    post:
      operationId: postSupplier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supplier
              properties:
                supplier:
                  $ref: "#/components/schemas/SupplierParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - supplier
                properties:
                  supplier:
                    $ref: "#/components/schemas/Supplier"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
  /api/v1/suppliers/{id}:
    get:
      operationId: getSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - supplier
                properties:
                  supplier:
                    $ref: "#/components/schemas/Supplier"
    patch:
      operationId: patchSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - supplier
              properties:
                supplier:
                  $ref: "#/components/schemas/SupplierParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - supplier
                properties:
                  supplier:
                    $ref: "#/components/schemas/Supplier"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
    delete:
      operationId: deleteSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"

  /api/v1/suppliers/${supplier_id}/products:
    get:
      operationId: getProducts
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - products
                properties:
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
    post:
      operationId: postProduct
      parameters:
        - name: supplier_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product
              properties:
                product:
                  $ref: "#/components/schemas/ProductParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - product
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
  /api/v1/products/${id}:
    get:
      operationId: getProduct
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - product
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
    patch:
      operationId: patchProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product
              properties:
                product:
                  $ref: "#/components/schemas/ProductParams"
      responses:
        "200":
          description: "success"
          content:
            application/json:
              schema:
                type: object
                required:
                  - product
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
        "422":
          description: "unprocessable entity"
          content:
            application/json:
              schema:
                type: object
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    items:
                      type: string
    delete:
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "success"

components:
  schemas:
    Supplier:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string

    SupplierParams:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    ProductParams:
      type: object
      required:
        - name
      properties:
        name:
          type: string
